# -*- mode: ruby -*-
# vi: set ft=ruby :

# I followed along here https://gorails.com/guides/using-vagrant-for-rails-development to create this

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3000, host:3000
  config.vm.network "forwarded_port", guest: 5000, host:5000

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end

  config.vm.provision :shell, path: "bootstrap.sh", privileged: false

end
